LambdaEventRule:
  Type: AWS::Events::Rule
  Properties:
    EventBusName: default
    EventPattern:
      detail-type:
        - AWS API Call via CloudTrail
      source:
        - aws.lambda
      detail:
        eventSource:
          - lambda.amazonaws.com
        eventName:
          - prefix: CreateFunction
          - prefix: UpdateFunctionConfiguration
          - prefix: TagResource
          - prefix: UntagResource
          - prefix: DeleteFunction
    Name: port-aws-exporter-sync-lambda-trails
    State: ENABLED
    Targets:
      - Id: PortAWSExporterEventsQueue
        Arn:
          Fn::ImportValue:
            Fn::Sub: ${PortAWSExporterStackName}-EventsQueueARN
        InputTransformer:
          InputPathsMap:
            awsRegion: $.detail.awsRegion
            eventName: $.detail.eventName
            requestFunctionName: $.detail.requestParameters.functionName
            requestResource: $.detail.requestParameters.resource
            responseFunctionName: $.detail.responseElements.functionName
          InputTemplate: |-
            {
              "resource_type": "AWS::Lambda::Function",
              "region": "\"<awsRegion>\"",
              "identifier": "if \"<responseFunctionName>\" != \"\" then \"<responseFunctionName>\" elif \"<requestResource>\" != \"\" then \"<requestResource>\" | split(\":\")[-1] else \"<requestFunctionName>\" end",
              "action": "if \"<eventName>\" | test(\"DeleteFunction[^a-zA-Z]*$\") then \"delete\" else \"upsert\" end"
            }